title: pont.cat
email: victor@pont.cat
description: >-
  My site
baseurl: "/"
url: "https://pont.cat"
twitter_username: vicibz
github_username: vpont
permalink: /:categories/:year/:month/:day/:title:output_ext

# Build settings
remote_theme: pages-themes/hacker@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
